Repository JungHJ99/2048_KAU, pull requests merged in 2024-06, with the labels that each got.

#20 Feat : 타임어택 모드 추가
  2048_game.c
Labels: 기능 추가

#21 Feat: 타임어택 모드 최고기록 추가
  2048_game.c
Labels: 기능 추가

#22 Fix: 분할 컴파일
  2048.c
  2048.h
  main.c
Labels: 클린코드

#29 Fix: 점수 기록 기능 개선 및 중괄호 및 들여쓰기 통일
  2048.c
  2048.h
  main.c
Labels: 클린코드, 추가 수정

#31 Fix: 게임 저장 기능 오류 수정
  2048.c
  main.c
Labels: 오류 수정
