Repository JungHJ99/2048_KAU, pull requests merged in 2024-05, with the labels that each got.

#10 Fix: 타이머 기능 개선
  2048_game.c
Labels: bug

#13 Add restart system
  2048_game.c
Labels: enhancement

#14 체크포인트 저장 및 불러오기 기능
  2048_game.c
Labels: enhancement

#15 [Fix] : Combined 위치 문제 및 점수 계산 해결
  2048_game.c
Labels: 오류 수정

#16 Feat: 실행 취소 기능 추가
  2048_game.c
Labels: 기능 추가

#17 Feat: 게임 기록 저장 기능 추가
  2048_game.c
Labels: 기능 추가
